# zhj

'''
Downloads SDSS cutout images into "cutouts" foler
coord.npy contains ra & dec of galaxies. The npy file is generated by read_catalog.ipynb, using UPenn_PhotDec_CAST.fits and UPenn_PhotDec_Mstar_mlMendel14.dat
nested try,except just in case sometimes the network connect of either local, or to SDSS database is not always stable.
images failed to download after 3 attempts are logged in error.npy
'''


import urllib.request
from tqdm import tqdm
import numpy as np
import time
import os

os.makedirs('cutouts')

coord=np.load('coord.npy')

try:
    err=np.load('error.npy')
except:
    err=[]


for i,co in tqdm(enumerate(coord),total=coord.shape[0]):
    url='http://skyserver.sdss.org/dr17/SkyServerWS/ImgCutout/getjpeg?ra='+str(co[0])+'&dec='+str(co[1])+'&width=64&height=64'
    try:
        urllib.request.urlretrieve(url, 'cutouts/'+str(i)+'.png')
    except:
        print('error: '+str(i)+'2nd try in 30s')
        time.sleep(30)
        try:
            urllib.request.urlretrieve(url, 'cutouts/'+str(i)+'.png')
        except:
            print('error: '+str(i)+'3rd try in 30s')
            time.sleep(30)
            try:
                urllib.request.urlretrieve(url, 'cutouts/'+str(i)+'.png')
            except:
                err=np.append(err,i)
                np.save('error.npy',err)
                pass
